version: '3.8'
services:
  pairing-server:
    build: .
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
      - PORT=3001
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_FROM_NUMBER=${TWILIO_FROM_NUMBER}
    ports:
      - "3001:3001"
